version: '3'
services:
  rwdb:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - /etc/localtime:/etc/localtime:ro
  adminer:
    image: adminer
    restart: unless-stopped
    container_name: adminer
    ports:
      - 8081:8080